plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.5.14' apply false
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.michelet'
version = '0.0.1-SNAPSHOT'


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

// 라이브러리이므로 Spring Boot 실행 파일(bootJar)은 비활성화, 일반 jar 만 생성
tasks.named('jar') {
    enabled = true
    archiveClassifier = ''
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.14"
    }
}

dependencies {
    // 공통 모듈이 제공하는 기능들에 필요한 최소 의존성
    // api 로 노출해서 서비스가 별도 선언 없이 바로 쓸 수 있게 함
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Lombok
    api 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Tracing 정보를 로그(MDC)로 연결
    api 'io.micrometer:micrometer-tracing-bridge-brave'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // 2. DB 및 Flyway (PostgreSQL)
    // 테스트에서 H2 쓸 경우 충돌할 수 있습니다. 그땐 api를 implementation으로 임시로 변경해주세요. ( 아마,..,,)
    api 'org.flywaydb:flyway-core'
    api 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'org.postgresql:postgresql'
}

test {
    useJUnitPlatform()
}

// Javadoc 경고 완화 (record 등)
javadoc {
    options.addStringOption('Xdoclint:none', '-quiet')
}

